@echo off
echo Starting Kafka pipeline demo components in PowerShell windows...

echo Starting Kafka Server...
start powershell -NoExit -Command "Set-Location -LiteralPath '%~dp0'; $env:KAFKA_HEAP_OPTS='-Xmx512M -Xms512M'; .\bin\windows\kafka-server-start.bat .\config\server.properties"

echo Waiting 25 seconds for Kafka to initialize...
timeout /t 25 /nobreak > nul

echo Starting Kafka Consumer...
start powershell -NoExit -Command "Set-Location -LiteralPath '%~dp0'; python consumer.py"

echo Starting Telegram Bot...
start powershell -NoExit -Command "Set-Location -LiteralPath '%~dp0'; python telegram_bot.py"

echo Starting FastAPI Backend...
start powershell -NoExit -Command "Set-Location -LiteralPath '%~dp0'; uvicorn backend.main:app --port 8000"

echo Starting React Frontend...
start powershell -NoExit -Command "Set-Location -LiteralPath '%~dp0\frontend'; npm run dev"

echo Starting Kafka Producer...
start powershell -NoExit -Command "Set-Location -LiteralPath '%~dp0'; python producer.py"

echo Demo environment (V2) launched!